---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mcp-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-mcp-server
    spec:
      containers:
        - name: app-mcp-server
          image: ghcr.io/prefeitura-rio/app-mcp-server:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: app-mcp-server-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: app-mcp-server
spec:
  selector:
    app: app-mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-mcp-server
  name: app-mcp-server
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: app-mcp-server
