---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: mcp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mcp
    spec:
      containers:
        - name: mcp
          image: ghcr.io/prefeitura-rio/app-mcp-server:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: mcp-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mcp
spec:
  selector:
    app: mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
